<?php
/**
 * Main constants.
 */

define( 'MAX_MARINE_EDIT_PRODUCT_SHARED_STATE_PLUGIN_VERSION', '2.0.0' );
define( 'MAX_MARINE_EDIT_PRODUCT_SHARED_STATE_DATABASE_VERSION', '10' );

define( 'MAX_MARINE_EDIT_PRODUCT_SHARED_STATE_PLUGIN_PATH', plugin_dir_path( __DIR__ ) );
define( 'MAX_MARINE_EDIT_PRODUCT_SHARED_STATE_PLUGIN_BASENAME', plugin_basename( __DIR__ ) );
define( 'MAX_MARINE_EDIT_PRODUCT_SHARED_STATE_PLUGIN_URL', trailingslashit( plugin_dir_url( __DIR__ ) ) );

define( 'MAX_MARINE_EDIT_PRODUCT_SHARED_STATE_PLUGIN_OPTIONS_KEY', 'MMEPSS_' );
